# Generated by Django 5.1.6 on 2025-02-21 13:51

import src.user.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                    ("RATHER_NOT_TO_SAY", "Rather Not To Say"),
                ],
                default=src.user.constants.Genders["RATHER_NOT_TO_SAY"],
                max_length=50,
                verbose_name="Gender",
            ),
        ),
    ]
