# Generated by Django 5.1.6 on 2025-02-21 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz",
            new_name="CourseQuiz",
        ),
        migrations.RenameModel(
            old_name="Answer",
            new_name="QuizAnswer",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="QuizQuestion",
        ),
    ]
