# Generated by Django 5.1.6 on 2025-02-21 15:48

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_rename_quiz_coursequiz_rename_answer_quizanswer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Parent category if this is a subcategory.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="course.category",
            ),
        ),
    ]
